apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node-bp
  namespace: platform-23-3-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node-bp
  template:
    metadata:
      labels:
        app: test-node-bp
    spec:
      containers:
      - name: test-node-bp
        image: ghcr.io/blinklabs-io/cardano-node
        ports:
        - containerPort: 3001
        - containerPort: 12798
        env:
        - name: CARDANO_NETWORK
          value: "preview"
        - name: RESTORE_SNAPSHOT
          value: "false"
        - name: CARDANO_BLOCK_PRODUCER
          value: "false"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        args: ["run"]
        volumeMounts:
        - name: efs-volume
          mountPath: /opt/cardano/config
          subPath: config  # Map to the "config" folder in the EFS mount
        - name: efs-volume
          mountPath: /opt/cardano/data
          subPath: data  # Map to the "data" folder in the EFS mount
      volumes:
      - name: efs-volume
        hostPath:
          path: /mnt/efs  # Root EFS mount
          type: Directory