apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node-bp
  namespace: platform-23-3-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node-bp
  template:
    metadata:
      labels:
        app: test-node-bp
    spec:
      nodeSelector:
        dedicated: test-node 
      containers:
      - name: test-node-bp
        image: ghcr.io/blinklabs-io/cardano-node
        ports:
        - containerPort: 3001
        #- containerPort: 12798
        env:
        - name: GENESIS_VERIFICATION_KEY
          value: "/opt/cardano/config/preview/genesis.vkey"
        - name: CARDANO_SOCKET_PATH
          value: "/opt/cardano/ipc/node.socket"
        - name: CARDANO_SHELLEY_KES_KEY
          value: "/opt/cardano/config/preview/keys/kes.skey"
        - name: CARDANO_SHELLEY_OPERATIONAL_CERTIFICATE
          value: "/opt/cardano/config/preview/keys/node.cert"
        - name: CARDANO_SHELLEY_VRF_KEY 
          value: "/opt/cardano/config/preview/keys/vrf.skey"

        - name: CARDANO_NETWORK
          value: "preview"
        - name: RESTORE_SNAPSHOT
          value: "false"
        - name: CARDANO_BLOCK_PRODUCER
          value: "true"
        resources:
          limits:
            memory: "4Gi"  # Set memory limit to 4GB
            cpu: "1.5"       # Set CPU limit to 2 cores
          requests:
            memory: "1Gi"  # Retain current memory request
            cpu: "500m"      # Adjust CPU request as needed
        args: ["run"]
        volumeMounts:
        - name: efs-volume
          mountPath: /opt/cardano/config
          subPath: config  # Map to the "config" folder in the EFS mount
        - name: efs-volume
          mountPath: /opt/cardano/data
          subPath: data  # Map to the "data" folder in the EFS mount
        - name: efs-volume
          mountPath: /opt/cardano/ipc
          subPath: ipc  # Map to the "data" folder in the EFS mount

      volumes:
      - name: efs-volume
        hostPath:
          path: /mnt/efslocal  # Root EFS mount
          type: Directory