apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-sync
  namespace: adrian-platform-24-1-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-sync
  template:
    metadata:
      labels:
        app: db-sync
    spec:
      containers:
      - name: db-sync
        image: ghcr.io/intersectmbo/cardano-db-sync:13.5.0.2
        env:
        - name: NETWORK
          value: "preview"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "cexplorer"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        volumeMounts:
        - name: db-sync-data
          mountPath: /var/lib
      volumes:
      - name: db-sync-data
        persistentVolumeClaim:
          claimName: db-sync-data