apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: efs-mounter
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: efs-mounter
  template:
    metadata:
      labels:
        app: efs-mounter
    spec:
      containers:
      - name: efs-mounter
        image: amazonlinux:latest
        command:
        - /bin/sh
        - -c
        - |
          dnf install -y amazon-efs-utils && \
          mkdir -p /mnt/efs && \
          mkdir -p /mnt/efslocal && \
          echo "enabled=false" > /etc/amazon/efs/efs-utils.conf.d/disable-watchdog.conf && \
          mount -t efs -o tls,region=eu-west-2 fs-08a9835fd0638f578 /mnt/efs && \
          while true; do sleep 30; done
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-mount
          mountPath: /mnt/efs
      volumes:
      - name: host-mount
        hostPath:
          path: /mnt/efs
          type: DirectoryOrCreate
      nodeSelector: {}
      tolerations:
      - operator: Exists