apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: adrian-platform-24-1-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.5
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: password123
        - name: POSTGRES_DB
          value: cexplorer
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: adrian-platform-24-1-x
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres