apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardano-data
  namespace: adrian-platform-24-1-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-sync-data
  namespace: adrian-platform-24-1-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: adrian-platform-24-1-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogmios-data
  namespace: adrian-platform-24-1-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kupo-data
  namespace: adrian-platform-24-1-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi